### ISSUE TITLE
Feature request- add support for 'jpg' backgrounds

### ISSUE THREAD

**Issue by iwubcode** [mmatyas/pegasus-theme-es2-simple#4]
Currently the background images only support png, it'd be nice if they support jpg as well.  Feels like it should be as easy as:

```
source: "bg/%1_art_blur.png".arg(modelData.shortName) || "bg/%1_art_blur.jpg".arg(modelData.shortName)
```

but that doesn't work.  I'm only guessing as I'm not familiar with QML

**Comment by mmatyas** [comment]
A theme doesn't know whether a file exists until it tries to access it -- which is why `||`-ing together the two paths together doesn't work. A logic could be added to check if it failed to load the first file, then try the next. It could also be improved to check the collection's background asset first.

Or, considering that all backgrounds are part of the theme anyway, you could just convert it to PNG :)

**Comment by iwubcode** [comment]
Yeah sorry, I didn't know if there was a simple QML option and admittedly was being a bit lazy.  Thank you for the response!
